DROP DATABASE IF EXISTS hyepye_main;
DROP DATABASE IF EXISTS hyepye_test;
DROP ROLE IF EXISTS hyepyeuser;

CREATE ROLE hyepyeuser WITH CREATEDB LOGIN ENCRYPTED PASSWORD 'hyepyepass';
CREATE DATABASE hyepye_main WITH OWNER=hyepyeuser TEMPLATE=template0 ENCODING='UTF8' LC_COLLATE='en_US.UTF-8' LC_CTYPE='en_US.UTF-8';
CREATE DATABASE hyepye_test WITH OWNER=hyepyeuser TEMPLATE=template0 ENCODING='UTF8' LC_COLLATE='en_US.UTF-8' LC_CTYPE='en_US.UTF-8';
